name: Deploy to Dev VPS

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEV_VPS_IP }}
          username: ${{ secrets.DEV_VPS_USERNAME }}
          key: ${{ secrets.DEV_VPS_SSH_KEY }}
          port: 22
          script: |
            # Project folder-e jao (Folder na thakle manually clone kore nite hobe prothom bar)
            cd /home/rup/OutdoorTherapyApp/OutdoorTherapyApp || exit

            # Code update kora
            # git pull origin dev
            git fetch --all
            git reset --hard origin/dev

            # Docker container refresh kora
            docker compose down --remove-orphans
            sleep 2
            docker compose up -d --build

            # Prisma database sync kora (Safe option)
            # docker compose exec -T api npx prisma db push